version: '3.8'

services:
  postgres:
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U root -d monitoramento-ar'" ]
      timeout: 45s
      interval: 10s
      retries: 5
    image: postgres:latest
    container_name: postgres-monitoramento-ar
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
      POSTGRES_DB: monitoramento-ar
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network-monitoramento-ar

  pgadmin:
    depends_on:
      postgres:
        condition: service_healthy
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "80:80"
    networks:
      - network-monitoramento-ar

  api-monitoramento:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    image: joaopalazzolli/monitoramento-ar:1.0
    container_name: api-monitoramento
    restart: always
    profiles: [ "dev" ]
    ports:
      - "8080:8080"
    networks:
      - network-monitoramento-ar

networks:
  network-monitoramento-ar:
    driver: bridge

volumes:
  data:
