version: '3.8'

services:
  mysql:
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 5
    image: mysql:latest
    container_name: "mysql-monitoramento"
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: monitoramentoar
    ports:
      - "3306:3306"
    volumes:
      - mysql-monitoramento:/var/lib/mysql
    networks:
      - network-monitoramento-ar

networks:
  network-monitoramento-ar:
    driver: bridge

volumes:
  mysql-monitoramento:
